# File: .github/workflows/ci.yml
# Purpose: PR CI for typecheck, lint, unit (Vitest) and e2e (Playwright all browsers)
# Node: latest stable; Package manager: npm

name: CI

on:
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Typecheck • Lint • Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (latest stable)
        uses: actions/setup-node@v5
        with:
          node-version: node            # tracks latest stable (a.k.a. "current")
          check-latest: true
          cache: npm                    # uses package-lock.json for cache key

      - name: Install dependencies
        run: npm ci

      - name: Typecheck (tsc --noEmit)
        run: npx tsc --noEmit

      - name: Lint (ESLint)
        run: npm run lint

      - name: Unit tests (Vitest)
        run: npm test

  e2e:
    name: Playwright • Chromium/Firefox/WebKit
    needs: unit
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (latest stable)
        uses: actions/setup-node@v5
        with:
          node-version: node
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Installs all Playwright browsers + OS dependencies
      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      - name: Run Playwright tests (all browsers)
        run: npm run test:e2e

      # Always upload the HTML report so it's easy to inspect failures
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
